### ISSUE TITLE
Image stitching

### ISSUE THREAD

**Issue by cherry956** [JialeWei/OneBEV#3]
Could you please provide the code for stitching the six perspective camera images in the nuScenes dataset? Thank you very much! We are also working on image stitching.@Jiale Wei

**Comment by JialeWei** [comment]
@cherry956 The stitching codes are already in repo. Folder: tools/stitch

**Comment by cherry956** [comment]
Thank you, I have already run it. For the nuScenes dataset, if we want to stitch the first three views' images and the last three views' images separately, can this method be implemented?@jiale Wei

**Comment by JialeWei** [comment]
@cherry956 Yes, our method can support stitching the first three views' images and the last three views' images separately. However, this would require some modifications to adapt the implementation for this specific use case.
